import os
import sys
from pathlib import Path

# Allow importing src.version when run from repo root
sys.path.insert(0, str(Path(__file__).resolve().parent))
from src.version import __version__


def _version_tuple(version: str):
    """'3.0.0' -> (3, 0, 0, 0)  (Windows version resources need 4 parts)."""
    parts = [int(p) for p in version.split(".") if p.isdigit()]
    parts = (parts + [0, 0, 0, 0])[:4]
    return tuple(parts)


def write_version_file(dest: Path, version: str) -> Path:
    """Generate a PyInstaller --version-file so the exe carries product/version metadata."""
    vt = _version_tuple(version)
    dest.parent.mkdir(parents=True, exist_ok=True)
    content = f"""# Auto-generated by build_exe.py — do not edit.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={vt},
    prodvers={vt},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          '040904B0',
          [
            StringStruct('CompanyName', 'dennokoworks'),
            StringStruct('FileDescription', 'Matcap Maker'),
            StringStruct('FileVersion', '{version}'),
            StringStruct('InternalName', 'MatcapMaker'),
            StringStruct('OriginalFilename', 'MatcapMaker.exe'),
            StringStruct('ProductName', 'Matcap Maker'),
            StringStruct('ProductVersion', '{version}')
          ])
      ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""
    dest.write_text(content, encoding="utf-8")
    return dest


def main():
    try:
        import PyInstaller.__main__
    except ModuleNotFoundError:
        print(
            "PyInstaller is not installed in the active Python environment. "
            "Install it with 'pip install PyInstaller' and run this script again.",
            file=sys.stderr,
        )
        return 1

    root_dir = Path(__file__).resolve().parent
    entry_script = root_dir / "src" / "main.py"
    icon_path = root_dir / "res" / "icon" / "icon.ico"
    shaders_dir = root_dir / "src" / "shaders"
    resources_dir = root_dir / "res"
    license_dir = root_dir / "LICENSE"

    sep = ';' if os.name == 'nt' else ':'

    version_file = write_version_file(root_dir / "build" / "version_info.txt", __version__)

    PyInstaller.__main__.run([
        str(entry_script),
        '--name=MatcapMaker',
        # onedir (default): installed under Program Files via the installer.
        '--noconsole',
        '--noconfirm',
        f'--icon={icon_path}',
        f'--version-file={version_file}',
        f'--distpath={root_dir / "dist"}',
        f'--workpath={root_dir / "build"}',
        f'--specpath={root_dir / "build"}',
        f'--add-data={shaders_dir}{sep}src/shaders',
        f'--add-data={resources_dir}{sep}res',
        f'--add-data={license_dir}{sep}LICENSE',
    ])
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
